### ISSUE TITLE
iRate was unable to open the App Store because the app store ID is not set

### ISSUE THREAD

**Issue by K232** [nicklockwood/iRate#132]
Hi all,
I'm using latest iRate 1.8 in my app (both iPhone and iPad). The app is already available in the AppStore. I've included a 'Rate now' button in my app but when I click on it it just runs to 'iRate was unable to open the App Store because the app store ID is not set'. As far as I've read nothing needs to be configured so it should run automatically, but it doesn't. Not in the simulator and not in the published app. Where do I need to check that the app store id is set correct?
Thanks!

**Comment by doriansgithub** [comment]
Hi Nick, after the new App store opened, we get this message, "Cannot Connect to App Store".
