### ISSUE TITLE
Prompt again each version

### ISSUE THREAD

**Issue by x2on** [nicklockwood/iRate#160]
Hi,

according to #142 and there is no status update i would like to ask for this feature again.
We are currently fork every version and re add this functionality which means a lot of overhead.

Currently if a user declined there is no option to ask him again in the next version. Also it's not possible to ask him on a new major version.

Shouldn't a developer decide if he activate this feature?

Would be nice to hear your opinion.

**Comment by zhangjianjun056** [comment]
@x2on ，Hello, I would like to ask that I was written in accordance with you, but still can not. All the version is still no longer prompted, when the click "no, thank you" button after
- (void)iRateDidDetectAppUpdate
{
    [iRate sharedInstance].declinedThisVersion = NO;
}

**Comment by zhangjianjun056** [comment]
@adamdehaven @nicklockwood  Hello, I would like to ask what I wrote, but still can not. All the version is still no longer prompted, when the click "no, thank you" button after. Do you have a good way?
-(void)iRateDidDetectAppUpdate
{
[iRate sharedInstance].declinedThisVersion = NO;
}
