### ISSUE TITLE
My App got rejected because of  iRate (1.11.3)

### ISSUE THREAD

**Issue by leofto** [nicklockwood/iRate#213]
My app has been approved before with iRate dependency. A new update has been rejected by Apple with the following reason:

We found that your app uses public APIs in a manner not prescribed by Apple, which is not in compliance with the iOS Developer Program License Agreement, as required by the App Store Review Guidelines.

In particular, section 3.3.1 of the iOS Developer Program License Agreement specifies:

"Applications may only use Documented APIs in the manner prescribed by Apple and must not use or call any private APIs"

Specifically we found this app misuses "canOpenURL:" to extrapolate which apps are installed on a device.

We appreciate that you may have made the precautions in your code for using these APIs in a non-prescribed way, however, there is no way to accurately or completely predict how an API may be modified and what effects those modifications may have. For this reason, we do not permit the non-prescribed use of public APIs in App Store apps.

The only place in my workspace that uses canOpenURL: is in iRate.m

    - (void)openRatingsPageInAppStore
    {
        if (!_ratingsURL && !self.appStoreID)
        {
            self.checkingForAppStoreID = YES;
            if (!self.checkingForPrompt)
            {
                [self checkForConnectivityInBackground];
            }
            return;
        }
    
        if ([[UIApplication sharedApplication] canOpenURL:self.ratingsURL])
        {
            if (self.verboseLogging)
            {
                NSLog(@"iRate will open the App Store ratings page using the following URL: %@", self.ratingsURL);
            }
        
            [[UIApplication sharedApplication] openURL:self.ratingsURL];
            [self.delegate iRateDidOpenAppStore];
            [[NSNotificationCenter defaultCenter] postNotificationName:iRateDidOpenAppStore
                                                            object:nil];
        }
        else
        {
             NSString *message = [NSString stringWithFormat:@"iRate was unable to open the specified ratings URL: %@", self.ratingsURL];
        
    #if TARGET_IPHONE_SIMULATOR
        
            if ([[self.ratingsURL scheme] isEqualToString:iRateiOSAppStoreURLScheme])
            {
                message = @"iRate could not open the ratings page because the App Store is not available on     the iOS simulator";
            }
        
    #endif
            NSLog(@"%@", message);
            NSError *error = [NSError errorWithDomain:iRateErrorDomain code:iRateErrorCouldNotOpenRatingPageURL userInfo:@{NSLocalizedDescriptionKey: message}];
            [self.delegate iRateCouldNotConnectToAppStore:error];
            [[NSNotificationCenter defaultCenter] postNotificationName:iRateCouldNotConnectToAppStore
                                                            object:error];
        }
    }

Has anyone had the same experience?

**Comment by nicklockwood** [comment]
Gah, more despicable app review bullshit. Try appealing it, since it's clearly not in violation - that check is only there so developers using iRate aren't confused when they try to run in on a simulator.

Meanwhile, I'll add a fix to remove that code and replace it with `#if TARGET_IPHONE_SIMULATOR` which will do the same job.

**Comment by leofto** [comment]
I don't know what the app review team is up to. They have been rejecting my apps for some ridiculous reasons. I feel like they have a quota of rejections they need to meet.

Thanks for the quick reply. I will try to appeal

**Comment by sfransen** [comment]
I agree my app was rejected 3 times in a row for stupid things

Two have them reasons have been there for three years now

**Comment by leofto** [comment]
uhm, turns out it is not iRate related.

I just back a response for my appeal. They specifically said the class MCiHasApp is the culprit. I think it is the Mobile Core ad framework. 

Sorry for the false alarm.

**Comment by nicklockwood** [comment]
OK, thanks!
