### ISSUE TITLE
Make a release for iOS9 including https URL (supporting App Transport Security)

### ISSUE THREAD

**Issue by glentregoning** [nicklockwood/iRate#222]
Make a release which includes this change (https://github.com/nicklockwood/iRate/commit/30a12ef08a974f6fb7ce7614402378e2461a090e)  to support App Transport Security in iOS9

**Comment by aramusss** [comment]
Please :+1:

**Comment by Legoless** [comment]
This is already fixed, just was not pushed to CocoaPods yet. @nicklockwood can you update?

**Comment by rdnx** [comment]
Looking forward to this release as well!

**Comment by Tagalong** [comment]
was it updated on cocoapods?

**Comment by Tibbs** [comment]
Any news on this?

**Comment by glentregoning** [comment]
Looks like this went out with 1.11.6 / 1.11.5
