### ISSUE TITLE
Add notification when new app version is available on App Store

### ISSUE THREAD

**Issue by jigmelam** [nicklockwood/iRate#236]
Please add notification when the new app version is available on App Store. I would like to prompt user to update the latest app version when available.
May be modify in this code statement: 
`//check version
                        if (self.onlyPromptIfLatestVersion && !self.previewMode)
                        {
                            NSString *latestVersion = [self valueForKey:@"version" inJSON:json];
                            if ([latestVersion compare:self.applicationVersion options:NSNumericSearch] == NSOrderedDescending)`

Thank so much!

**Comment by nicklockwood** [comment]
I have another library called iVersion that does exactly what you're asking for. You can use it together with iRate in the same project.

**Comment by jigmelam** [comment]
Thank you!
