### ISSUE TITLE
Missing TAG for HEAD. Carthage is not working due to this

### ISSUE THREAD

**Issue by racer1988** [nicklockwood/iRate#258]
Hello,

last tag is more than 1 year ago,
in order for carthage to work #221 
we need to release a new version.

Thank you

**Comment by nicklockwood** [comment]
I'd guess this is fixed now? I don't use Carthage those so please confirm.

**Comment by racer1988** [comment]
*** Checking out iRate at "1.11.6"

Yep! Good Job! Thanks a lot for this :D
