### ISSUE TITLE
Crash in checkForConnectivityInBackground (iOS7)

### ISSUE THREAD

**Issue by AlexanderMarkevich** [nicklockwood/iRate#260]
`
dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0), ^{
     [self checkForConnectivity];
});
`

QOS_CLASS_BACKGROUND available for iOS8 +.

**Comment by nicklockwood** [comment]
Thanks for bringing this to my attention. Fixed in 1.11.6
