### ISSUE TITLE
"checkForConnectivity" function   crash

### ISSUE THREAD

**Issue by kakashilw** [nicklockwood/iRate#272]
in   "checkForConnectivity"   function，the  line  "  if (error && !(error.code == EPERM && [error.domain isEqualToString:NSPOSIXErrorDomain] && _appStoreID))  "   sometimes  crash , and show info"accessing _cachedSystemAnimationFence requires the main thread"

**Comment by nicklockwood** [comment]
Should be fixed in 1.11.7. Thanks!
