### ISSUE TITLE
Get bundle id smarter

### ISSUE THREAD

**Issue by blackcolt** [nicklockwood/iRate#275]
Why don't you get the bundleIdentifier like so:

iRate.sharedInstance().applicationBundleID = Bundle.main.bundleIdentifier! as String

**Comment by nicklockwood** [comment]
iRate sets the bundle ID automatically using

    [[NSBundle mainBundle] bundleIdentifier]

Which is equivalent to the code you pasted. You only need to set it manually yourself if you want to override it for some reason.
