### ISSUE TITLE
iRate and Swift 3.1 project 

### ISSUE THREAD

**Issue by siberianisaev** [nicklockwood/iRate#282]
`Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions` https://github.com/nicklockwood/iRate/blob/master/README.md#installation

**Comment by ptsimpso** [comment]
I'm also wondering about the solution for this. This seems to be a possible option: http://stackoverflow.com/questions/24137212/initialize-class-method-for-classes-in-swift

But I'd love to hear from those more familiar with the project for a final implementation.

**Comment by siberianisaev** [comment]
Yeah think can be override `init` method of app delegate

**Comment by mknippen** [comment]
I'm not sure this one should be closed yet. Since 3.1 now generates a warning for every user using iRate, we should probably come up with the solution that makes the most sense and update the documentation.

**Comment by nicklockwood** [comment]
Fixed in 1.12
