### ISSUE TITLE
SKStoreReviewController is not used in manual prompt request

### ISSUE THREAD

**Issue by djachenko** [nicklockwood/iRate#298]
According to code, iOS 10.3+ rate popup can only be requested if both SKStoreReviewController is available and `manual` flag is set to `NO`:
```
if (!manual && [SKStoreReviewController class])
{
    [self remindLater];
    [SKStoreReviewController requestReview];
}
```
But in `- promptForRating` method this flag is unconditionally set to `YES`:
```
- (void)promptForRating
{
    [self promptForRating: YES];
}
```
At the same time `- promptForRating:` is unavailable from public interface of iRate. The result is that SKStoreReviewController's popup can never be shown in explicit review request from code. Is this the intentional design or an issue?

**Comment by nicklockwood** [comment]
It's intentional. Apple says that you should never show SKStoreReviewController using a user-facing button because it's not guaranteed to appear.

**Comment by djachenko** [comment]
Well, I understand the idea and agree with it. But then is there any way to make popup appear at some point in control flow? Everything's OK if it doesn't appear, flow will go on, but if it does, it better be at this particular moment. `logEvent:NO` can make the thing done, but method itself looks like designed for other purpose. Maybe some other method without any guarantees that popup will be shown, like SKStoreReviewController's `requestReview`, will be more suitable for such case.

**Comment by djachenko** [comment]
Oh. I've overlooked some parts of interface designed for manual review requesting. I'm sorry for disturbance.
